name: Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      start_image:
        description: 'Start Image'
        required: true
        default: 'icubteamcode/ubuntu2004mesa:master_sources'
      superbuild_release:
        description: 'Robotology Superbuild Release'
        required: true
        default: 'master'
      ultrapython_release:
        description: 'UltraPython Release'
        required: true
        default: 'master'
      add_tag_latest:
        description: 'Add tag latest to the docker image'
        required: true
        default: 'yes'
      build_type:
        description: 'Build Type'
        required: true
        default: 'Release'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Require tag latest
      id: add_tag_latest
      if: ${{ github.event.inputs.add_tag_latest == 'yes' }}
      run: |
        echo "::set-output name=tag::, latest"
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@main
      env:
        START_IMG: ${{ github.event.inputs.start_image }}
        ROBOTOLOGY_SUPERBUILD_RELEASE: ${{ github.event.inputs.superbuild_release }}
        ULTRAPYTHON_RELEASE: ${{ github.event.inputs.ultrapython_release }}
        BUILD_TYPE:  ${{ github.event.inputs.build_type }}
      with:
        name: robotology/yarp-device-ultrapython
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        workdir: dockerfiles
        buildargs: START_IMG, ROBOTOLOGY_SUPERBUILD_RELEASE, ULTRAPYTHON_RELEASE, BUILD_TYPE
        registry: ghcr.io
        tags: "${{ github.event.inputs.superbuild_release }}_${{ github.event.inputs.ultrapython_release }}${{ steps.add_tag_latest.outputs.tag }}"